# fly.toml app configuration file generated for twedsa-patient-dew-4157 on 2024-04-22T17:31:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'twedsa-patient-dew-4157'
primary_region = 'ewr'

[build]

[build.args]
  CAISY_PROJECT_ID='4aebde9c-c273-4dba-b0c0-25e8f00edc43'
  CAISY_API_KEY='Y5rr06qkiOfyR0TvyG4UMxjQaGxSHFkh'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
